version: '3'

services:
  database:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      - MARIADB_USER=amin
      - MARIADB_PASSWORD=aminzare
      - MARIADB_ROOT_PASSWORD=aminzare
      - MARIADB_DATABASE=test

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - redis
      - database
    # uncomment this to use .env file
    # env_file: 
    #   - ./server/.env

  client: 
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - server
    # uncomment this to use .env file
    # env_file:
    #   - ./client/.env