version: '3'

services:
  database:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      - MARIADB_USER=amin
      - MARIADB_PASSWORD=aminzare
      - MARIADB_ROOT_PASSWORD=aminzare
      - MARIADB_DATABASE=test

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    
  server:
    build: 
      # target: next-build
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - DATABASE_HOST=database
      - DATABASE_DIALECT=mariadb
      - DATABASE_PORT=3306
      - DATABASE_USER=amin
      - DATABASE_PASSWORD=aminzare
      - JWT_SECRET=%@%3OEvPWD6L3X5^%m4RjG&lbooYJbGAT
      - JWT_EXPIRE=600h
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - database

  client: 
    build: 
      # target: next-build
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - SERVER_URI=http://localhost:5000
    depends_on:
      - server