name: Docker Compose

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        ports:
          - 2375:2375
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and run Docker Compose
        run: |
          docker-compose up -d --build
